export const Images = {
    IKSANA_LOGO: "/Images/iksana_logo.png",
    PHONE_LOGO: "/Images/Phone_logo.png",

};

export const Strings = {
    THE_BEST_QUALITY: "THE BEST QUALITY.",
    THE_BEST_GUARANTEES: "THE BEST GUARANTEES.",
    PARAGRAPH1: "Lorem ipsum dolor sit amet consectetur adipisicing sum dolor sit amet consectetu sectetur adipisici sectetur adipisici ipsum dolor sit amet consectetur adipisicing sum dolor sit amet consectetu sectetur adipisici sectetur  consectetu sectetur adipisici sectetu.",

    BRANCHES: "KEMPS CORNER | DADAR | JUHU | ANDHERI",
    ALL_RIGHTS: "2024 IKSANA OPTICALS | All Rights Reserved",
    SERVICES: "SERVICES",
    EYE_TESTING: "EYE TESTING",
    EXPERT_DOCTOR: "EXPERT DOCTOR CONSULTATION",
    ACCOUNT: "ACCOUNT",
    PROFILE: "PROFILE",
    APPOINTMENTS: "APPOINTMENTS",
    ORDERS: "ORDERS",
    PAYMENT: "PAYMENT",
    RETURNS_REFUNDS: "RETURNS & REFUNDS",
    ABOUT_US: "ABOUT US",
    OUR_HISTORY: "OUR HISTORY",
    BLOG: "BLOG",
    CONTACT_US: "CONTACT US",
    USEFUL_LINKS: "USEFUL LINKS",
    STORE_LOCATION: "STORE LOCATION",
    BUSINESS_PARTNERS: "BUSINESS PARTNERS",
    SUBSCRIBE_NEWSLETTER: "SUBSCRIBE TO OUR NEWSLETTER",
    NEED_HELP: "NEED HELP?",
    CALL_US: "CALL US ON",
    PHONE: " +91 82912 51241",
    FAQ: "FAQs",
    TERMS: "Terms & Conditions",
    PRIVACY: "Privacy Policy",
    SUBSCRIBED_SUCCESSFULLY: "You have subscribed successfully.",


    EXCHANGE_POLICY: 'Exchange and refund policy',
    PART_EASY_EXC: 'Part A: EASY EXCHANGE/REFUND POLICY- 14 DAYS FOR',
    EYEGLASSES_7_DAYS: 'EYEGLASSES & 7 DAYS FOR SUNGLASSES',
    PRIVACY_1PARA: "We are committed to providing you high quality products. In a rare event, if you aren't fully satisfied with our product and find it is not 'As described' on our website, or is received in a 'damaged' condition, you can request an Exchange or Refund within 14 days of receiving the order for eyeglasses and within 7 days of receiving the order for sunglasses for Iksana Opticals LLP  in-house brands. We allow exchange/refund with the following exceptions:",
    CONTACT_LENSES: "Contact Lenses:",
    EYEWEAR: "Eyewear:",
    PARTIAL_BOGO: "Partial Return in BOGO:",
    ACCESORIES_LENS: "Accessories (Lens cleaner, contact lens case, contact lens solution & others):",
    UL1_L1: "These would be acceptable only if they are in unworn condition, with the sealed outer packaging intact within 14 days in exceptional cases through customer support centre. Contact Lenses can only be refunded, not exchanged.",
    UL1_L2: "[Eyeglasses, Sunglasses, Reading Glasses] with the following are not accepted for exchange/refund:",
    UL1_L3: "Scratches on frame or lens that were not present at the time of delivery. We do a rigorous 3-step quality check to ensure that the product reaches you in perfect condition.",
    UL1_L4: "Product damaged due to mishandling post delivery [product is de-shaped, with visible intentional damage to the product].",
    UL1_L5: "Eyewear case or other standard packaging is damaged or torn or otherwise not in the same condition as it was received.",
    UL1_L6: "Refund/ exchange is not allowed on accessories.",
    UL1_L7: "Partial returns are entitled for exchange and store credits only if Buy One Get One offer is availed. To avail complete refund, all the products in the order need to be refund requested.",
    UL2_L1: "Take your product with all its accessories to the selected store",
    UL2_L2: "Iksana Opticals llp store will inspect the product. You can get your glasses adjusted at the store",
    UL2_L3: "If required you can exchange the product or get a refund as per our policy",
    UL3_L1: "Keep the products with all accessories ready for pickup.",
    UL3_L2: "You can choose a product for exchange Or take refund as per policy",
    UL3_L3: "Exchange product will be dispatched/refund will be credited once the returned item reaches us",
    UL4_L1: "Pack the products and stick the return label on the box. We will email you the label",
    UL4_L2: "Select any courier service & ship the product to Iksana Opticals llp at the given address. (We will reimburse you upto Rs100 once the product is received)",
    UL4_L3: "You can choose a product for exchange or take a refund as per policy once the returned item reaches us.",
    UL5_L1: "With the same frame & same lens package -Get a fresh piece of the same frame & lens package ( or coating if added)",
    UL5_L2: "With the same frame but a different lens package- Get a fresh piece of the same frame & upgrade to a different lens package ( or coating) and any additional amount for the upgrade will have to be paid.",
    UL5_L3: "With a different frame & different lens package- Choose from a wide range of different frame & different lens packages & the difference amount from the new product and old product will have to be paid",
    UL6_L1: "Instantly credited in your account after pick-up",
    UL6_L2: "Use against any product",
    UL6_L3: "Use online & in stores",
    UL6_L4: "6 Month validity",
    UL7_L1: "You will get a refund back to the original source through which the product was purchased e.g. E.g. If you paid through Rs. 100 through Store Credit and Rs. 1500 through debit Card, then the amount i.e. Rs. 100 and Rs. 1500 will be refunded in Store credit and debit card respectively",
    UL7_L2: "The amount will be credited to your account in 1-5 business days in case of wallets/debit card and 7-10 days in case of credit card payment once the product has reached us in its original condition",
    UL8_L1: "You will be asked to fill your UPI/bank details to get the refund. Once the Iksana Opticals llp receives the product, a link will be shared with you to share your bank/UPI details.",
    UL8_L2: "The amount will be credited to your account in 24 hours",
    UL9_L1: "You must have initiated the exchange/refund process within 14 days from receipt of your product.",
    UL9_L2: "No Cash refund will be provided for Cash On Delivery orders",
    UL10_L1: "Reach out to us via “Contact Us/Need Help” option on the Website or Apps.",
    UL10_L2: "You can also reach out to us on +91-7977994474",
    HOW_TO_RETURN: "How to return?",
    VISIT_NEAR_STORE: "Vist the nearest store",
    SCHEDULE_PICKUP: "Schedule a Pick-Up",
    PER_PICKUP_FREE: "100% Free Pick-up service: Available in select cities.",
    WE_ARRANGE_PICKUP:"We would arrange a pick-up at your location within 2-5 days thereafter.",
    SHIP_PRODUCT_IKSHANA: "Ship Product to Iksana Opticals llp",
    EXCHANGE_AND_REFUND: "Exchange & Refund Options:",
    EXCHANGE_OPTIONS: "Exchange Options (Most Popular):",
    YOU_CAN_FOLLOWING_EXCHANGE: "You can do the following types of exchange:",
    REFUND_OPTIONS: "Refund Options:",
    REFUND_OPTION_PARA: "If you don’t wish to exchange your product, you can choose to receive the refund amount of your product in the following ways:",
    STORE_CREDIT: "Store Credit",
    REFUND_TO_SOURCE: "Refund to source",
    REFUND_TO_SOURCE_PARA: "Note: If the amount is paid via StoreCredit + Online, then the amount will go into SC and original payment method respectively.",
    TRANSFER_TO_BANK: "Transfer to Bank (available for Cash on Delivery online orders or Offline orders only)",
    NOTE: "Note :",
    PART_B: "Part B: CANCELLATION POLICY",
    PART_B_PARA: "We custom make each lens specifically for you - we can't reuse a lens cut for you, for anyone else, should you choose to cancel your order. However, we want you to be able to try us 100% risk-free. Thereafter, if you would like to cancel your order before if has reached you, for any reason you, please choose to contact us at the following:",
    PART_C: "Part C: FAQs",
    FREQUENTLY_ASKED_QUES: "Frequently Asked Questions",
    Q1: "1. What is Store Credit?",
    A1: "Store credit is an amount issued to customers in lieu of the orders returned to Iksana Opticals llp . This amount can be used to place a new or a replacement order from Iksana Opticals llp.",
    Q2: "2. Where will I get the option for exchange or replacement of my order?",
    A2: "In “Your Orders”, Click on “View Order Details, You will get, ’Exchange/Refund’ option as per Iksana Opticals llp Policy.",
    Q3: "3. Will I be able to get a refund for my order before the product reaches the Iksana Opticals llp warehouse?",
    A3: "No, the refund can only be issued once we receive the order in our warehouse.",
    Q4: "4. If the order was paid via Cash on Delivery, then what option do I need to select for refund?",
    A4: "You need to select from the following two options:",
    Q5: "5. In case of return, can I arrange pick up from two different addresses for an order containing two products?",
    A5: "Yes, you can edit the address or add a different address to both the products while initiating the reverse pickup from My Account.",
    Q6: "6. If I return the product at Iksana Opticals llp  store, then when will I get a refund?",
    A6: "The refund request will be initiated once you handover the product at the store. Amount will get credited in 0-2 days",
    Q7: "7. Can a customer change the refund method after initiating the return?",
    A7: "No.",
    Q8: "8. In case I have purchased two products under Buy One Get One Offer, then can I get a refund for one product?",
    A8: "No, you can only get a replacement. If you face any difficulty, please inform us using “Need Help”/”Contact Us” option on the Website or Apps.",
    Q9: "9. When will exchange order be dispatched?",
    A9: "The exchange order will be dispatched once the returned product reaches Iksana Opticals llp and is approved by the team.",
    Q10: "10. Video’s before sending.",
    A10: " We have to take video of parcel products before sending them to customers.",
    TRANSFER_TO_BANK_UPI: "Transfer to bank (UPI available)",

}
