// layout.tsx

import { CartProvider } from "@/Context/CartContext";
import Head from "next/head";
import React from "react";

interface LayoutProps {
  children: React.ReactNode;
  title?: string;
}

const metadata = {
  title: "iksana Opticals",
  description: "Generated by Next.js",
};

const RootLayout: React.FC<LayoutProps> = ({ children, title }) => {
  return (
    <>
      <html lang="en">
        <Head>
          <title>{title}</title>
        </Head>
        <body>
          <CartProvider>{children}</CartProvider>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
